name: Build and Push Docker Images
on:
  push:
    branches:
      - main

# needed to push to ghcr.io
permissions: 
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/preston4tw/c7test:latest
            ghcr.io/preston4tw/c7test:amd64
            ghcr.io/preston4tw/c7test:arm64
          platforms: linux/amd64,linux/arm64
          # https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # cache-from: type=registry,ref=preston4tw/c7test:latest
          # cache-to: type=inline
          # cache-from: type=registry,ref=preston4tw/c7test:buildcache
          # cache-to: type=registry,ref=preston4tw/c7test:buildcache,mode=max
